name: Publish Extension
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://api.samepage.network
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.SAMEPAGE_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SAMEPAGE_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
  OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
  OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: build
        run: npx samepage build
